CREATE USER SA PASSWORD ""
GRANT DBA TO SA
CREATE SCHEMA "test" AUTHORIZATION DBA
ALTER USER SA SET INITIAL SCHEMA "test"
SET WRITE_DELAY 10
SET SCHEMA "test"
create table F1 (F1_id INT NOT NULL, D1_id INT NOT NULL)
create table D1(D1_id INT NOT NULL,D1_description VARCHAR(10) NOT NULL)
create table F2( F2_id INT NOT NULL, D2_id INT NOT NULL)
create table D2( D2_id INT NOT NULL, D2_description VARCHAR(10) NOT NULL, D2_rollup VARCHAR(10) NOT NULL)
create table F3( F3_id INT NOT NULL, D1_id INT NOT NULL, D2_id INT NOT NULL, F3_value NUMERIC)
insert into F1 values (1,1)
insert into F1 values (2,1)
insert into F1 values (3,2)
insert into D1 values (1,'D1 One')
insert into D1 values (2,'D1 Two')
insert into F2 values (1,1)
insert into F2 values (2,2)
insert into F2 values (3,3)
insert into D2 values (1,'D2 One', 'D2 A')
insert into D2 values (2,'D2 Two', 'D2 A')
insert into D2 values (3,'D2 Three', 'D2 B')
insert into F3 values (1,1,1,10)
insert into F3 values (2,1,2,20)
insert into F3 values (3,2,3,35)